04-Empleados/applications/empleados/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "persona_app"


urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('lista-by-area/<shorname>', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path(
        'lista-empleados-admin/',
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadoDetailView.as_view(), name="empleado_detail"),
    path(
        'success/',
        views.SuccessView.as_view(),
        name='correcto'
    ),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),
]

04-Empleados/empleado/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos la url de la app departamento
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.empleados.urls')),
    re_path('', include('applications.departamento.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

04-Empleados/applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=20)

04-Empleados/templates/persona/add.html
<h1>Registrar Persona</h1>

<form method="POST">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Agregar</button>
</form>

04-Empleados/templates/persona/by_kword.html
<h1>Buscar empleados por palabra clave</h1>

<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>

<h3>Lista resultados</h3>
<ul>
    
    {% for e in empleados  %}
        <li>{{e}}</li>
    {% endfor %}
        
</ul>

04-Empleados/templates/persona/delete.html
<h1>Eliminar</h1>

<form method="post">{% csrf_token %}
    <p>COnfirme que desea eliminar</p>
    <button type="submit">Confirmar</button>
</form>

04-Empleados/templates/persona/detail_empleado.html
<h1>Detalle de un empleado del mes</h1>

{{first_name}}

04-Empleados/templates/persona/habilidades.html
<h1>Habilidades de empelado</h1>

<ul>
    
    {% for h in habilidades %}
        <li>{{ h }}</li>
    {% endfor %}
        
</ul>

04-Empleados/templates/persona/list_all.html
<h1>Lista de empleados</h1>

<ul>
    {% for e in empleados %}
        <li>{{ e }}</li>
    {% endfor %}
</ul>

04-Empleados/templates/persona/list_by_area.html
{% extends 'base.html' %}

{% block title %}
  lista empelados por departamento
{% endblock title %}

{% block content %}
  {% include "includes/header.html" %}

  <div class="container">
      <div class="row">
        <h2 class="mt-3">Empelados por area:</h2>
        <div class="row">
            <table class="table mt-10">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">NOMBRES</th>
                    <th scope="col">APELLIDOS</th>
                    <th scope="col">DEPARTAMENTO</th>
                    <th scope="col">ACCION</th>
                </tr>
                </thead>
                <tbody>
                {% for e in empleados %}
                <tr>
                    <td>{{e.id}}</td>
                    <td>{{e.first_name}}</td>
                    <td>{{e.last_name}}</td>
                    <td>{{e.departamento}}</td>
                    <td><a class="btn btn-primary" href="{% url 'persona_app:empleado_detail' e.id %}" role="button">Ver</a></td>
                </tr> 
                {% endfor %}
                </tbody>
            </table>
        </div>
        
      </div>
  </div>


{% endblock content %}

<h1>Lista empelados por departamento</h1>

<ul>
    
    {% for e in object_list  %}
        <li>{{ e }}</li>
    {% endfor %}
        
</ul>

04-Empleados/templates/persona/lista_empleados.html
{% extends 'base.html' %}

{% block content %}
{% include "includes/header.html" %}

<div class="container">
    <h1 class="mt-3">Lista de empleados</h1>

        <div class="col">
            <table class="table mt-10">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">NOMBRES</th>
                    <th scope="col">APELLIDOS</th>
                    <th scope="col">DEPARTAMENTO</th>
                    <th scope="col">ACCION</th>
                </tr>
                </thead>
                <tbody>
                {% for e in empleados %}
                <tr>
                    <td>{{e.id}}</td>
                    <td>{{e.first_name}}</td>
                    <td>{{e.last_name}}</td>
                    <td>{{e.departamento}}</td>
                    <td><a class="btn btn-success" href="{% url 'persona_app:modificar_empleado' e.id %}" role="button">Editar</a></td>
                    <td><a class="btn btn-danger" href="{% url 'persona_app:eliminar_empleado' e.id %}" role="button">Eliminar</a></td>
                </tr> 
                {% endfor %}
                </tbody>
            </table>
        </div>
        
    </div>

    <div class="row">
        <nav aria-label="Page navigation example">
             {% if is_paginated %}
             <ul class="pagination justify-content-center">
              {% if page_obj.has_previous %}  
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.previous_page_number}}" tabindex="-1" aria-disabled="true">Atras</a>
                </li>
              {% endif %}

              <li class="page-item active"><a class="page-link" href="?page={{ pagina }}">{{ page_obj.number }}</a></li>
    
              
              {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.next_page_number}}" tabindex="-1" aria-disabled="true">Siguiente</a>
                </li>
              {% endif %}
             </ul>
            {% endif %}
          </nav>
    </div>
    

</div>

{% endblock content%}

04-Empleados/templates/persona/success.html
<h1>Felicitaciones, se guardo correctamenet el empleado</h1>

04-Empleados/templates/persona/update.html
{% extends 'base.html' %}

{% block title %}
  Editar Empelado
{% endblock title %}

{% block content %}

{% include "includes/header.html" %}

<div class="container">
    <h2 class="mt-3">Modificar Datos de Empleado</h2>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <label for="id_nombre" class="form-label">Nombre:
                    {{ form.first_name }}
                </label>
            </div>
            
            <div class="col-md-6">
                <label for="id_email" class="form-label">Apellidos:</label>
                {{ form.last_name }}
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-md-6">
                <label for="id_nombre" class="form-label">Trabajo:</label>
                {{ form.job }}
            </div>
            
            <div class="col-md-6">
                <label for="id_email" class="form-label">Area:</label>
                {{ form.departamento }}
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-md-6">
                <label for="id_nombre" class="form-label">Habilidades extra:</label>
                {{ form.habilidades }}
            </div>
        </div>

        <div class="col">
            <button type="submit" class="btn btn-success">Guardar</button>
        </div>
        
    </form>
</div>

{% endblock content %}











<!--
<h1>Modificar Datos de Empleado</h1>

<form method="POST">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Actualizar</button>
</form>
-->