04-Empleados/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "departamento_app"

urlpatterns = [
    path(
        'departamento-lista/',
        views.DepartamentoListView.as_view(),
        name='departamento_list'),
    path(
        'new-departamento/',
        views.NewDepartamentoView.as_view(),
        name='nuevo_departamento'
    ),
]

04-Empleados/applications/empleados/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "persona_app"


urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('lista-by-area/<shorname>', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path(
        'lista-empleados-admin/',
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadoDetailView.as_view(), name="empleado_detail"),
    path(
        'success/',
        views.SuccessView.as_view(),
        name='correcto'
    ),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),
]

04-Empleados/empleado/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos la url de la app departamento
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.empleados.urls')),
    re_path('', include('applications.departamento.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

04-Empleados/templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Empleados</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'persona_app:empleados_all' %}">Listar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'departamento_app:departamento_list' %}">Departamentos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'persona_app:empleados_admin' %}">Administrar</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Buscar empleado" aria-label="Search">
          <button class="btn btn-outline-light text-nowrap" type="submit">Registrar Nuevo</button>
        </form>
      </div>
    </div>
  </nav>